# Generated by Django 3.0.14 on 2021-05-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceimage',
            name='image',
            field=models.ImageField(upload_to='resources/images/83093967/'),
        ),
    ]
