# Generated by Django 3.0.14 on 2021-06-02 11:01

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_auto_20210531_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='detail',
            field=martor.models.MartorField(),
        ),
    ]
