# Generated by Django 3.0.14 on 2021-06-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_auto_20210602_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='categories',
            field=models.ManyToManyField(help_text='Use Ctrl key and select as many categories you wish to choose. 😎', related_name='resources', to='info.ResourceCategory'),
        ),
    ]
