# Generated by Django 3.0.4 on 2020-06-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(default='B.Tech', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.IntegerField(default=3),
        ),
    ]
