-- Bank_data Database

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS cdcrc;
CREATE SCHEMA cdcrc
DEFAULT CHARACTER SET utf8;
USE cdcrc;

--
-- Table structure for table `cdcrc_events`
--

CREATE TABLE cdcrc_events (
	event_id INT NOT NULL AUTO_INCREMENT,
	display_text VARCHAR(200) NOT NULL,
	link VARCHAR(150) DEFAULT '#',
	type VARCHAR(5),
	PRIMARY KEY (event_id)
);

CREATE TABLE cdcrc_news (
	news_id INT NOT NULL AUTO_INCREMENT,
	display_text VARCHAR(200) NOT NULL,
	link VARCHAR(150) DEFAULT '#',
	type VARCHAR(5),
	PRIMARY KEY (news_id)
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
