# Generated by Django 3.0.5 on 2020-06-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20200606_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
