# Generated by Django 3.0.14 on 2021-05-20 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(null=True)),
                ('address', models.TextField(null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('domain', models.CharField(blank=True, choices=[('sde', 'SDE'), ('core', 'Core'), ('non_core', 'Non Core')], max_length=40, null=True)),
                ('visible', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDemographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ugp', 'UG for Placement'), ('pgp', 'PG for Placement'), ('ugi', 'UG for Internships'), ('pgi', 'PG for Internships')], max_length=10)),
                ('strength', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Department')),
            ],
        ),
        migrations.CreateModel(
            name='JAF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongo_id', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruiter.Recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='INF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongo_id', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruiter.Recruiter')),
            ],
        ),
    ]
