# Generated by Django 3.0.5 on 2020-06-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
    ]
