FROM nginx:1.19.0-alpine

RUN rm -f /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/nginx.conf

# USE the following for prod: 
# main.sh script altomatically appends the string below: :)
# COPY nginx_with_ssl.conf /etc/nginx/conf.d/nginx.conf

