# Generated by Django 3.0.14 on 2021-05-20 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('suffix', models.CharField(blank=True, max_length=254, null=True)),
                ('job_title', models.CharField(blank=True, max_length=254, null=True)),
                ('phone_one', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_two', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recruiter', models.CharField(blank=True, max_length=254, null=True)),
                ('remark', models.CharField(blank=True, max_length=512, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=10)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('initial_comment', models.TextField()),
                ('next_reminder', models.DateTimeField(blank=True, null=True)),
                ('assignees', models.ManyToManyField(blank=True, related_name='assigned_issues', to='profiles.TeamMemberProfile')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to='profiles.TeamMemberProfile')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiter_issues', to='recruiter.Recruiter')),
                ('student_concerned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concerned_issues', to='profiles.StudentProfile')),
            ],
        ),
        migrations.CreateModel(
            name='IssueFollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('followup_time', models.DateTimeField(auto_now=True)),
                ('assignees', models.ManyToManyField(related_name='assigned_followups', to='profiles.TeamMemberProfile')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='internal.Issue')),
            ],
        ),
    ]
