# Generated by Django 3.0.14 on 2021-05-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisibilityconfig',
            name='page',
            field=models.CharField(choices=[('pd_about', 'pd_about'), ('pd_activities', 'pd_activities'), ('pd_library', 'pd_library'), ('pd_videos', 'pd_videos'), ('cr_about', 'cr_about'), ('cr_activities', 'cr_activities'), ('cr_hod_message', 'cr_hod_message'), ('pd_hod_message', 'pd_hod_message'), ('tnp_hod_message', 'tnp_hod_message'), ('pd_initiatives', 'pd_initiatives')], max_length=128, unique=True),
        ),
    ]
