# Generated by Django 3.0.4 on 2020-06-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('course', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=1)),
            ],
        ),
    ]
