# Generated by Django 3.0.14 on 2021-05-20 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('domain', models.CharField(blank=True, choices=[('sde', 'Software Development'), ('core', 'Core'), ('non-core', 'Non Core'), ('general', 'General')], max_length=32, null=True)),
                ('category', models.CharField(blank=True, choices=[('pg', 'Post Graduate'), ('ug', 'Under Graduate'), ('staff', 'Staff'), ('faculty', 'Faculty')], max_length=32, null=True)),
                ('designation', models.CharField(blank=True, max_length=64, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', validators=[utils.validators.validate_file_size, utils.validators.validate_file_extension])),
                ('visible', models.BooleanField(default=False)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=12, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('graduating_year', models.IntegerField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
